version: '3.8'

services:
  postgres-account:
    container_name: postgres-account
    image: postgres:16
    environment:
      POSTGRES_DB: account_db
      POSTGRES_USER: account
      POSTGRES_PASSWORD: password
    volumes:
      - postgres-account-data:/var/lib/postgresql/data
    ports:
      - "5450:5432"
    restart: unless-stopped

  postgres-account-test:
    container_name: postgres-account-test
    image: postgres:16
    environment:
      POSTGRES_DB: account_test_db
      POSTGRES_USER: account
      POSTGRES_PASSWORD: password
    ports:
      - "5451:5432"
    restart: unless-stopped

  postgres-transaction:
    container_name: postgres-transaction
    image: postgres:16
    environment:
      POSTGRES_DB: transaction_db
      POSTGRES_USER: transaction
      POSTGRES_PASSWORD: password
    volumes:
      - postgres-transaction-data:/var/lib/postgresql/data
    ports:
      - "5452:5432"
    restart: unless-stopped

  mongo-transaction:
    container_name: mongodb-audit-logs
    image: mongo:7.0
    environment:
      MONGO_INITDB_DATABASE: transaction_db
      MONGO_INITDB_ROOT_USERNAME: transaction
      MONGO_INITDB_ROOT_PASSWORD: password
    ports:
      - "27020:27017"
    volumes:
      - mongo-audit-data:/data/db
    restart: unless-stopped

  kafka:
    container_name: fincore-kafka
    image: confluentinc/cp-kafka:latest
    ports:
      - "9092:9092"
    environment:
      KAFKA_NODE_ID: 1
      KAFKA_PROCESS_ROLES: broker, controller
      KAFKA_CONTROLLER_QUORUM_VOTERS: '1@localhost:9093'
      KAFKA_LISTENERS: 'PLAINTEXT://0.0.0.0:9092,CONTROLLER://0.0.0.0:9093'
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_CLUSTER_ID: 4L62YDgVSOe6649zI7qWJw
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
    volumes:
      - kafka-fincore:/var/lib/kafka/data

  mongodb-notification:
    container_name: mongodb-notification-storage
    image: mongo:7.0
    environment:
      MONGO_INITDB_DATABASE: notification_db
      MONGO_INITDB_ROOT_USERNAME: notification
      MONGO_INITDB_ROOT_PASSWORD: password
    ports:
      - "27022:27017"
    volumes:
      - mongo-notification-data:/data/db
    restart: unless-stopped

volumes:
  postgres-account-data:
  postgres-transaction-data:
  mongo-audit-data:
  kafka-fincore:
  mongo-notification-data: