version: '3.8'

services:
  postgres-account:
    container_name: postgres-account
    image: postgres:16
    environment:
      POSTGRES_DB: account_db
      POSTGRES_USER: account
      POSTGRES_PASSWORD: password
    volumes:
      - postgres-account-data:/var/lib/postgresql/data
    ports:
      - "5450:5432"
    restart: unless-stopped
    networks:
      - fincore-network

  postgres-account-test:
    container_name: postgres-account-test
    image: postgres:16
    environment:
      POSTGRES_DB: account_test_db
      POSTGRES_USER: account
      POSTGRES_PASSWORD: password
    ports:
      - "5451:5432"
    restart: unless-stopped
    networks:
      - fincore-network

  postgres-transaction:
    container_name: postgres-transaction
    image: postgres:16
    environment:
      POSTGRES_DB: transaction_db
      POSTGRES_USER: transaction
      POSTGRES_PASSWORD: password
    volumes:
      - postgres-transaction-data:/var/lib/postgresql/data
    ports:
      - "5452:5432"
    restart: unless-stopped
    networks:
      - fincore-network

  mongo-transaction:
    container_name: mongodb-audit-logs
    image: mongo:7.0
    environment:
      MONGO_INITDB_DATABASE: transaction_db
      MONGO_INITDB_ROOT_USERNAME: transaction
      MONGO_INITDB_ROOT_PASSWORD: password
    ports:
      - "27020:27017"
    volumes:
      - mongo-audit-data:/data/db
    restart: unless-stopped
    networks:
      - fincore-network
  kafka:
    container_name: fincore-kafka
    image: confluentinc/cp-kafka:latest
    ports:
      - "9092:9092"
    environment:
      KAFKA_NODE_ID: 1
      KAFKA_PROCESS_ROLES: broker, controller
      KAFKA_CONTROLLER_QUORUM_VOTERS: '1@fincore-kafka:9093'
      KAFKA_LISTENERS: 'PLAINTEXT://0.0.0.0:9092,CONTROLLER://0.0.0.0:9093'
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://fincore-kafka:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_CLUSTER_ID: 4L62YDgVSOe6649zI7qWJw
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
    volumes:
      - kafka-fincore:/var/lib/kafka/data
    networks:
      - fincore-network

  mongodb-notification:
    container_name: mongodb-notification-storage
    image: mongo:7.0
    environment:
      MONGO_INITDB_DATABASE: notification_db
      MONGO_INITDB_ROOT_USERNAME: notification
      MONGO_INITDB_ROOT_PASSWORD: password
    ports:
      - "27022:27017"
    volumes:
      - mongo-notification-data:/data/db
    restart: unless-stopped
    networks:
      - fincore-network

  redis-transaction:
    container_name: redis-transaction-storage
    image: redis:7.0
    volumes:
      - redis-transaction:/data
    ports:
      - "6343:6379"
    restart: unless-stopped
    networks:
      - fincore-network

  redis-account:
    container_name: redis-account-storage
    image: redis:7.0
    volumes:
      - redis-account:/data
    ports:
      - "6344:6379"
    restart: unless-stopped
    networks:
      - fincore-network

  postgres-keycloak:
    container_name: postgres-keycloak
    image: postgres:16
    environment:
      POSTGRES_DB: keycloak_db
      POSTGRES_USER: keycloak
      POSTGRES_PASSWORD: password
    ports:
      - "5453:5432"
    volumes:
      - postgres-keycloak-data:/var/lib/postgresql/data
    restart: unless-stopped
    networks:
      - fincore-network

  keycloak:
    container_name: fincore-keycloak
    image: quay.io/keycloak/keycloak:26.2
    command:
      - start-dev
    environment:
      KC_DB: postgres
      KC_DB_URL_HOST: postgres-keycloak
      KC_DB_URL_DATABASE: keycloak_db
      KC_DB_USERNAME: keycloak
      KC_DB_PASSWORD: password

      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin

    ports:
      - "9090:8080"

    depends_on:
      - postgres-keycloak

    restart: unless-stopped
    networks:
      - fincore-network

  account-service:
    build:
      context: .
      dockerfile: account-service/Dockerfile
    container_name: account-service
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres-account:5432/account_db
      SPRING_DATASOURCE_USERNAME: account
      SPRING_DATASOURCE_PASSWORD: password
      SPRING_DATA_REDIS_HOST: redis-account
      SPRING_DATA_REDIS_PORT: 6379
      SPRING_KAFKA_PRODUCER_BOOTSTRAP_SERVERS: fincore-kafka:9092
      SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_ISSUER_URI: http://fincore-keycloak:8080/realms/fincore
    depends_on:
      - postgres-account
      - redis-account
      - kafka
      - keycloak
    restart: unless-stopped
    networks:
      - fincore-network

  transaction-service:
    build:
      context: .
      dockerfile: transaction-service/Dockerfile
    container_name: transaction-service
    ports:
      - "8082:8082"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres-transaction:5432/transaction_db
      SPRING_DATASOURCE_USERNAME: transaction
      SPRING_DATASOURCE_PASSWORD: password
      SPRING_DATA_MONGODB_HOST: mongodb-audit-logs
      SPRING_DATA_MONGODB_PORT: 27017
      SPRING_DATA_REDIS_HOST: redis-transaction
      SPRING_DATA_REDIS_PORT: 6379
      SPRING_KAFKA_PRODUCER_BOOTSTRAP_SERVERS: fincore-kafka:9092
      SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_ISSUER_URI: http://fincore-keycloak:8080/realms/fincore
      ACCOUNT_SERVICE_URL: http://account-service:8080
    depends_on:
      - postgres-transaction
      - mongo-transaction
      - redis-transaction
      - kafka
      - account-service
    restart: unless-stopped
    networks:
      - fincore-network

  notification-service:
    build:
      context: .
      dockerfile: notification-service/Dockerfile
    container_name: notification-service
    ports:
      - "8084:8084"
    environment:
      SPRING_DATA_MONGODB_HOST: mongodb-notification-storage
      SPRING_DATA_MONGODB_PORT: 27017
      SPRING_KAFKA_CONSUMER_BOOTSTRAP_SERVERS: fincore-kafka:9092
    depends_on:
      - mongodb-notification
      - kafka
    restart: unless-stopped
    networks:
      - fincore-network

  gateway-service:
    build:
      context: .
      dockerfile: fincore-gateway/Dockerfile
    container_name: gateway-service
    ports:
      - "8085:8085"
    environment:
      SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_ISSUER_URI: http://fincore-keycloak:8080/realms/fincore
      ACCOUNT_SERVICE_URL: http://account-service:8080
      TRANSACTION_SERVICE_URL: http://transaction-service:8082
    depends_on:
      - account-service
      - transaction-service
      - keycloak
    restart: unless-stopped
    networks:
      - fincore-network

volumes:
  postgres-account-data:
  postgres-transaction-data:
  mongo-audit-data:
  kafka-fincore:
  mongo-notification-data:
  redis-transaction:
  redis-account:
  postgres-keycloak-data:

networks:
  fincore-network:
    driver: bridge