version: '3.8'

services:
  postgres-account:
    container_name: postgres-account
    image: postgres:16
    environment:
      POSTGRES_DB: account_db
      POSTGRES_USER: account
      POSTGRES_PASSWORD: password
    volumes:
      - postgres-account-data:/var/lib/postgresql/data
    ports:
      - "5450:5432"
    restart: unless-stopped

  postgres-account-test:
    container_name: postgres-account-test
    image: postgres:16
    environment:
      POSTGRES_DB: account_test_db
      POSTGRES_USER: account
      POSTGRES_PASSWORD: password
    ports:
      - "5451:5432"
    restart: unless-stopped

  postgres-transaction:
    container_name: postgres-transaction
    image: postgres:16
    environment:
      POSTGRES_DB: transaction_db
      POSTGRES_USER: transaction
      POSTGRES_PASSWORD: password
    volumes:
      - postgres-transaction-data:/var/lib/postgresql/data
    ports:
      - "5452:5432"
    restart: unless-stopped

  mongo-transaction:
    container_name: mongodb-audit-logs
    image: mongo:7.0
    environment:
      MONGO_INITDB_DATABASE: transaction_db
      MONGO_INITDB_ROOT_USERNAME: transaction
      MONGO_INITDB_ROOT_PASSWORD: password
    ports:
      - "27020:27017"
    volumes:
      - mongo_audit_data:/data/db
    restart: unless-stopped

volumes:
  postgres-account-data:
  postgres-transaction-data:
  mongo_audit_data: